### ISSUE TITLE
Runtime Error:  Expected object of scalar type Long but got scalar type Byte for argument #2 'target'

### ISSUE THREAD

**Issue by immkapoor** [vkhoi/KTH-Action-Recognition#8]
Loading Dataset
Start training
Traceback (most recent call last):
  File "train_cnn_single_frame.py", line 59, in <module>
    validate=True, resume=resume, use_cuda=cuda)
  File "D:\Action Recognition\KTH Program\KTH-Action-Recognition-master\KTH-Action-Recognition-master\main\train_helper.py", line 109, in train
    loss = criterion(outputs, labels)
  File "C:\Users\Meghna\Anaconda\envs\tensorflow_env\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Meghna\Anaconda\envs\tensorflow_env\lib\site-packages\torch\nn\modules\loss.py", line 904, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "C:\Users\Meghna\Anaconda\envs\tensorflow_env\lib\site-packages\torch\nn\functional.py", line 1970, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "C:\Users\Meghna\Anaconda\envs\tensorflow_env\lib\site-packages\torch\nn\functional.py", line 1790, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: Expected object of scalar type Long but got scalar type Byte for argument #2 'target'

**Comment by ashuezy** [comment]
Add this line

labels = labels.long()

in the train method before calling criterion(....

**Comment by immkapoor** [comment]
@ashuezy Hi, I tried adding this line yet I am getting same error.

**Comment by jaycelol10** [comment]
where to put the line ?

**Comment by jaycelol10** [comment]
@ashuezy  @vkhoi  @immkapoor  can you please tell me how u solved it guys ?
